### ISSUE TITLE
TELNET Shell Server Example  build error

### ISSUE THREAD

**Issue by CodyGuo** [reiver/go-telnet#2]
.\main.go:8: imported and not used: "fmt"
.\main.go:19: undefined: telsh.Context
.\main.go:20: cannot use fiveHandler (type func(io.ReadCloser, io.WriteCloser, io.WriteCloser) error) as type telsh.HandlerFunc in argument to telsh.PromoteHandlerFunc
.\main.go:60: undefined: telsh.Context
.\main.go:62: cannot use danceHandler (type func(io.ReadCloser, io.WriteCloser, io.WriteCloser) error) as type telsh.HandlerFunc in argument to telsh.PromoteHandlerFunc
.\main.go:81: cannot convert fiveProducer (type func(<T>, string, ...string) telsh.Handler) to type telsh.ProducerFunc
.\main.go:87: cannot convert danceProducer (type func(<T>, string, ...string) telsh.Handler) to type telsh.ProducerFunc
.\main.go:91: cannot convert danceProducer (type func(<T>, string, ...string) telsh.Handler) to type telsh.ProducerFunc

**Comment by creasyimm** [comment]
same error

**Comment by poojakar** [comment]
Can anyone suggest me how to send command 'status' with telnet in go client?

**Comment by MikhailMS** [comment]
In case someone still interested in how to run the Shell Server example:

1. change Handler functions to match signature 
`(stdin io.ReadCloser, stdout io.WriteCloser, stderr io.WriteCloser, args ...string)`
2. change Producer functions to match signature 
`(ctx telnet.Context, name string, args ...string)`

**Comment by Newbetek** [comment]
Since such a simple fix in the instructions on how to use the package has not been fixed in a year and a half, I'm thinking that this package has been abandoned?

**Comment by reiver** [comment]
@Newbetek No, it hasn't been abandoned.

I got busy building a bank for the last 3 years.

(I've never built a bank before. It is very interesting.)

Thanks for commenting. It made me look at this package again.

I'll take a look.

**Comment by reiver** [comment]
@CodyGuo @creasyimm @poojakar @MikhailMS @Newbetek 

I updated the docs.

**If you have time, please check to see that the code (that you cared about) in the docs works now.**

I'm going to close this issue.

**If you find there are still problems, please open a new issue.**

(BTW... if you notice I am unresponsive here, you can always ping me on Twitter. My username there is the same as my GitHub userna.e)
